package schildt_proj.Exception_Handling;

/**
 * Created by RI on 6/1/2017.
 *
 * Exception can be generated by methods and also can be handled by another methods
 *
 */
public class ExcTest {

    static void genException(){
        int num[] = new int[4];
        System.out.println("Before exception is generated.");
        num[7] = 100;
        System.out.println("This won't be displayed.");
    }


    public static void main(String args[]){
        /*
        * let's handle the exception from main method
        **/
        try {
            System.out.println();
            ExcTest.genException();

        }catch (ArrayIndexOutOfBoundsException exception){
            System.out.println("This was out of bound call.");
        }
        System.out.println("Outside catch block.");
    }
}
